# Jakarta-specific overrides

global:
  region: jakarta

deployment:
  replicaCount: 6

resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi

autoscaling:
  minReplicas: 4
  maxReplicas: 20

nodeSelector:
  workload: high-performance

env:
  - name: AWS_REGION
    value: "ap-southeast-3"
  
  - name: DATABASE_PROXY_ENDPOINT
    value: "nusantaramart-proxy.proxy-xxxxxxxx.ap-southeast-3.rds.amazonaws.com"
  
  - name: REDIS_ENDPOINT
    value: "nusantaramart-redis.xxxxxx.clustercfg.apse3.cache.amazonaws.com"