{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nusantaramart-app.fullname" . }}-{{ .Values.deployment.color }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nusantaramart-app.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nusantaramart-app.selectorLabels" . | nindent 6 }}
      version: {{ .Values.deployment.color }}
{{- end }}